### ISSUE TITLE
Moodle 3.8.1

### ISSUE THREAD

**Issue by patocius** [projectestac/moodle-mod_jclic#10]
The last version of the plugin 3.0.3 not work on Moodle 3.8.1.
When you add the jclic activity by zip or url moodle not show the jclic application.

Any help?

thank you in advance.

**Comment by jequinterosa** [comment]
no sirve en la vercion 3.8 ayuda por favor

**Comment by frncesc** [comment]
I have identified a bug in jclic.js (the engine that runs JClic activities on the browser) related to this issue.

Hope to have a solution soon!

**Comment by frncesc** [comment]
I have updated [jclic.js](/projectestac/jclic.js) to version 1.1.13, solving an issue related to [Babel-polyfill](https://babeljs.io/docs/en/next/babel-polyfill) observed on Moodle 3.8.

Please check if it works now.
