### ISSUE TITLE
Extend field lang from jclic table to allow the language name to be saved longer than 10 characters

### ISSUE THREAD

**Issue by tmas0** [projectestac/moodle-mod_jclic#12]
Hi team!
We have a problem with the **lang** field from to **jclic** table. It's defined to 10 characters, but the language name can be more than 10 characters, for example **ca_valencia** (11 chars).

Can you extend the lang field to allow all lang names to be saved?

- **lang**: ca_valencia -> 11 chars.
- **field definition**: `<FIELD NAME="lang" TYPE="char" LENGTH="10" NOTNULL="false" SEQUENCE="false"/>`

Kind regards

**Comment by frncesc** [comment]
You are right, the `lang` field should allow locales with language, country and variant.
According to [RFC 5646](https://tools.ietf.org/html/rfc5646), a length of 30 characters should be enough for normal language tags.
Working on it!

**Comment by frncesc** [comment]
Solved in https://github.com/projectestac/moodle-mod_jclic/commit/18debc5bf7839f517f82920fd4b1f43c23547252
Tests on MySql and PostgreSQL passed, so closing this issue.
