### ISSUE TITLE
Error Moodle 2.7 under https

### ISSUE THREAD

**Issue by nachoan** [projectestac/moodle-mod_jclic#2]
Hi,

When using a https ssl 443 port url Jclic doen't connect with database.

This error was long time solved but it's now here. 
Error connecting to the reports database!
Error on line 1: white spaces are requiered between publicid and systemid

Moodle 2.7.1 and Jclic Module 0.2.4

**Comment by crazyserver** [comment]
Have you tried latest version 0.2.5? PLease confirm this version is also failing to work on that.

**Comment by nachoan** [comment]
It's working now. Thank you!
