### ISSUE TITLE
Cannot load the JClic project

### ISSUE THREAD

**Issue by oertel** [projectestac/moodle-mod_jclic#3]
Moodle 2.7.7+ (Build: 20150313)
JClic v0.2.5 (2015031300)
Since a few days we (must) use a https encrypted Moodle site - on the same unencrypted Moodle site before everything was fine.

I have created a JClic activity with an uploaded valid JClic zip-file and selected the preview. The following error message appears during loading:

![error](https://cloud.githubusercontent.com/assets/6482225/6748245/ef7ab6b4-cee3-11e4-8041-74bcc61cbb3d.jpg)

The path is valid and the file exists. All of our present JClic activities doesn't work anymore :worried:

The general settings for the JClic activity are the (new) default settings:

![settings](https://cloud.githubusercontent.com/assets/6482225/6748316/98788818-cee4-11e4-95b9-19ef9701731e.jpg)

I purged the Moodle cache and the browser cache, but it does not change anything.

**Comment by crazyserver** [comment]
Hi!

Try to change these params to http again.
To see what's going on, can you also attatch us the html code is generating? (with the <div id="jclic_applet"> and its contents will be  enough)

Thanks!

**Comment by oertel** [comment]
Hi crazyserver,

thanks for your efforts.

I think I found a possible reason. In IE11 it works as expected (but we recommend to use other browsers) and in Firefox, Chrome, Opera it doesn't work. The reason seems to be a special setting in the security options in Moodle: __Site administration > Security > HTTP security__
If you check the option _Only http cookies_, the JClic only works in IE and in the other browsers the described error occurs.  I have unchecked the option and after the next Moodle login everything works fine.

Thanks, Stefan
=> Not a really bug :smirk:

**Comment by crazyserver** [comment]
It seems very strage! We've tested in those browsers (we also recommend that). We will take a look :)

Thanks for your report!

**Comment by crazyserver** [comment]
Hi Stefan,
It seems that this problem cannot be solved with the current situation. The VM cannot accés the cookie when accessing Moodle and the only solution is to disable this option.

However we're glad to tell you that we're working on a HTML5 based solution of JClic so, in a near future,  this will be solved!

Regards,

Pau
