### ISSUE TITLE
Undefined index: $HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by oertel** [projectestac/moodle-mod_jclic#4]
Hi folks,
we use a newer Version of PHP (5.6.8) and since 5.6.0 the feature `$HTTP_RAW_POST_DATA` is marked as deprecated (see http://php.net/manual/en/reserved.variables.httprawpostdata.php).

That's why we get two PHP errors in `/jclic/action/beans.php` on lines 35 and 38. You should use `php://input` instead. Usually in a new `php.ini` the parameter `always_populate_raw_post_data` is set to -1 what means, that only the new method `php://input` is supported (see http://php.net/manual/en/ini.core.php#ini.always-populate-raw-post-data).

Thanks, Stefan

**Comment by crazyserver** [comment]
Hi Stephan! Thanks for your interest!

We're working on that issue for the Moodle 2.8 version, however if you are using some other version please tell us so we can cherry-pick the solution in older branches.

**Comment by oertel** [comment]
Hi Pau,
thanks for your reply.

At the moment we use Moodle 2.7.8. During our summer holidays in July we will upgrade to Moodle 2.9. So it would be fine if you do an upgrade, but it is not necessary :smirk: Currently it is only a PHP Notice.

Thanks, Stefan

**Comment by crazyserver** [comment]
Thanks!

Please test the current 2.8 version on 2.7 and tell us if is workking for you :-)

Cheers

**Comment by crazyserver** [comment]
Now on master branch, closing!
