### ISSUE TITLE
Is there any plan to support moodle 3.x?

### ISSUE THREAD

**Issue by nacc** [projectestac/moodle-mod_jclic#6]
Hello,

Ubuntu 16.04 currently packages version 0.2.3 of jclicmoodle, but it seems to only be intended to support moodle 2.x. We are moving to moodle 3.0.3 as 16.04 will only support PHP7.0. Would it be preferable to drop the Ubuntu package or will there be moodle 3.x support in the next week or two (that's the rough timeline here)?

-Nish

**Comment by sarjona** [comment]
Hi!

From the official plugins page of Moodle (https://moodle.org/plugins/pluginversions.php?plugin=mod_jclic) you can download the last version of this plugin which should work with Moodle 3.0 :-)

When you install it, if you have some problem, tell us to review it.

Best wishes from Barcelona,
Sara
